### ISSUE TITLE
Can the thinkeropenmm.py give paramters for nonstandard amino acid residues?

### ISSUE THREAD

**Issue by zhengcheng233** [Inniag/openmm-scripts-amoeba#1]
In the origin opemm, the amoeba force field only provides the parameters for  stardard amino acid residues. 
So can the python script tinker2opennmm.py used to generate amoeba force field of nonstandrard amino acid residue?

**Comment by Inniag** [comment]
- The script does not generate new parameters, it merely converts parameters specified in Tinker file format to the XML format used by OpenMM. So you would need your nonstandard amino acid residues specified in Tinker format for this script to be useful.
- Currently, the script does not implement external bonds, so will not be able to convert polymer residues fully. You should see a warning to this effect if you attempt conversion of Tinker files that contain external bond statements.
- If you want to extent the script with this functionality, I am happy to accept a pull request.

**Comment by Inniag** [comment]
No PR submitted.
